pipeline {
    agent {
        docker {
            image 'python:3.11-slim' // Python pre-installed
            args '-u root:root'      // run as root to install dependencies
        }
    }

    environment {
        VENV_DIR = 'venv'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/ochogwuprince92/alx-backend-python.git',
                    credentialsId: 'github-credentials'
            }
        }

        stage('Setup Python') {
            steps {
                sh """
                python3 -m venv ${VENV_DIR}
                . ${VENV_DIR}/bin/activate
                pip3 install --upgrade pip
                pip3 install -r requirements.txt
                """
            }
        }

        stage('Run Tests') {
            steps {
                sh """
                . ${VENV_DIR}/bin/activate
                pytest tests/ --junitxml=report.xml
                """
            }

            post {
                always {
                    junit 'report.xml'  // Archive test results
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished'
        }
    }
}
