pipeline {
    agent any

    environment {
        VENV_DIR = 'venv'
    }

    stages {
        stage('Checkout') {
            steps {
                // Pull code from GitHub using the credentials you added
                git branch: 'main',
                    url: 'https://github.com/ochogwuprince92/alx-backend-python.git',
                    credentialsId: 'github-credentials'
            }
        }

        stage('Setup Python') {
            steps {
                // Create virtual environment and install dependencies
                sh """
                python3 -m venv ${VENV_DIR}
                . ${VENV_DIR}/bin/activate
                pip3 install --upgrade pip
                pip3 install -r messaging_app/requirements.txt
                """
            }
        }

        stage('Run Tests') {
            steps {
                // Run pytest and generate a JUnit-style report
                sh """
                . ${VENV_DIR}/bin/activate
                pytest tests/ --junitxml=report.xml
                """
            }

            post {
                always {
                    // Archive the test report for Jenkins UI
                    junit 'report.xml'
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished'
        }
    }
}
