pipeline {
    agent any

    environment {
        VENV = "${WORKSPACE}/venv"
        REPORT = "${WORKSPACE}/report.xml"
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out code from GitHub...'
                checkout scm
            }
        }

        stage('Verify Structure') {
            steps {
                echo 'Verifying project structure...'
                sh 'ls -R'
            }
        }

        stage('Set Up Python') {
            steps {
                echo 'Creating virtual environment and installing dependencies...'
                sh '''
                    python3 -m venv $VENV
                    . $VENV/bin/activate
                    pip3 install --upgrade pip
                    pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Django Admin Check') {
            steps {
                echo 'Running Django checks...'
                sh '''
                    . $VENV/bin/activate
                    python messaging_app/manage.py check
                '''
            }
        }

        stage('Run Code Quality') {
            steps {
                echo 'Running flake8 linting...'
                sh '''
                    . $VENV/bin/activate
                    flake8 messaging_app/
                '''
            }
        }

        stage('Run Tests') {
            steps {
                echo 'Running pytest...'
                sh '''
                    . $VENV/bin/activate
                    pytest messaging_app/chats/tests.py --junitxml=$REPORT
                '''
            }
            post {
                always {
                    junit "$REPORT"
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Building Docker image...'
                sh '''
                    docker build -t your-dockerhub-username/messaging-app:latest messaging_app/
                '''
            }
        }

        stage('Push Docker Image') {
            steps {
                echo 'Pushing Docker image to Docker Hub...'
                withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                        docker push your-dockerhub-username/messaging-app:latest
                    '''
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished!'
        }
        success {
            echo 'Pipeline succeeded!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
