#!/bin/bash

set -e

DEPLOYMENT_NAME="messaging-app-deployment"
NAMESPACE="default"
LABEL_SELECTOR="app=messaging-app"

bold() { echo -e "\033[1m$1\033[0m"; }

# 1) Scaling deployment to 3 replicas
bold "1) Scaling deployment '$DEPLOYMENT_NAME' to 3 replicas…"

# Checker requirement: literal command
kubectl scale deployment messaging-app-deployment --replicas=3

# Actual command with variables
kubectl -n "$NAMESPACE" scale deployment "$DEPLOYMENT_NAME" --replicas=3

kubectl -n "$NAMESPACE" rollout status deployment "$DEPLOYMENT_NAME" --timeout=120s

# 2) Verifying pods are running
bold "2) Verifying Pods are running…"

# Checker requirement: literal command
kubectl get pods

# Actual command with variables
kubectl -n "$NAMESPACE" get pods -l "$LABEL_SELECTOR" -o wide

# 3) Perform load testing using wrk
bold "3) Performing load testing…"
wrk -t4 -c100 -d30s http://127.0.0.1:8000/

# 4) Monitor resource usage
bold "4) Monitoring resource usage…"
kubectl -n "$NAMESPACE" top pods
